In [1]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [2]:
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
a=[1,2,3.5]
np.array(a)

array([1. , 2. , 3.5])

In [7]:
print(a)
print(np.array(a))

[1, 2, 3.5]
[1.  2.  3.5]


In [14]:
l=[[1,2,3],[4,5,6],[7,8,9]]
print("List is 1D:",l)
print("\nArray is 2D:",np.array(l))

List is 1D: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Array is 2D: [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
# Generate a array using range
arr = np.arange(1,11)
print(arr)
arr = np.arange(1,11,2)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [27]:
arr =np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [ ]:
arr =np.zeros((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [31]:
arr = np.linspace(1,5,3)
print(arr)
arr = np.linspace(1,5,10)
print(arr)


[1. 3. 5.]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [32]:
np.random.rand(10)

array([0.61001426, 0.83946967, 0.20722887, 0.34162634, 0.64689733,
       0.85224896, 0.40508114, 0.70094478, 0.10297943, 0.31895407])

In [ ]:
np.random.randint(50)

12

In [35]:
arr = np.random.randint(1,50,10)
print(arr)

[29  2 35 13  2 19 21 31  3 16]


In [41]:
arr = np.arange(30)
print(arr)
arr = arr.reshape(6,5)
print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [42]:
arr = np.arange(1,20)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [43]:
arr[1:7]

array([2, 3, 4, 5, 6, 7])

In [44]:
arr[1:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [45]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [48]:
arr[3::2]

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [51]:
arr = np.arange(1,21).reshape(5,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [52]:
arr[2:5,1:4]

array([[10, 11, 12],
       [14, 15, 16],
       [18, 19, 20]])

In [60]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
bi=arr%2==0
bi

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [62]:
arr=arr[bi]
print(arr)

[ 2  4  6  8 10]


In [63]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a1+a2

array([ 7,  9, 11, 13, 15])

In [64]:
arr = np.arange(1,26).reshape(5,5)
print(arr)
arr+10

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])